name: BuildAndDeploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: npm run build
    - name: Updating Domain
      run: echo "Update domain"
    - name: Deploy to GH Pages
      run: |
      git config --global user.email ${{secrets.GH_EMAIL}}
      git config --global user.name ${{secrets.GH_USERNAME}}
      git remote set-url origin https://${{secrets.GH_ACCESS_TOKEN}}@github.com/${{secrets.GITHUB_USERNAME}}/jsboardgamedemo.git
      echo git status