name: BuildAndDeploy
on: [push]
env:
  TO_DEPLOY_REPO: ${{secrets.GH_USERNAME}}/jsboardgamedemo
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: ${{env.GITHUB_REF_SLUG}} - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}

      - name: Node - Setup ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Node - Install Packages
        run: npm install

      - name: Node - Build and Pack App
        run: npm run build
     
      - name: App - Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./docs/dist

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Git - Global Configuration
        run: |
          git config --global user.email ${{secrets.GH_EMAIL}}
          git config --global user.name ${{secrets.GH_USERNAME}}

      - name: ${{env.GITHUB_REF_SLUG}} - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}

      - name: ${{env.TO_DEPLOY_REPO}} - Checkout master
        uses: actions/checkout@v2
        with:
          repository: ${{env.TO_DEPLOY_REPO}}
          token: ${{secrets.GH_ACCESS_TOKEN}}
          path: docs/dist
          ref: master

      - name: ${{env.TO_DEPLOY_REPO}} - Delete Content
        run: |
          cd ./docs/dist
          git rm -r .

      - name: "App - Artifact Download"
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./docs/dist

      - name: ${{env.TO_DEPLOY_REPO}} - Deploy
        run: |
          cd ./docs/dist
          git add .
          git commit -m "CD-${{github.run_id}}: deployed pages" | true
          git push -f | true
