name: BuildAndDeploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Checkout Branch
      run: |
        cd ./docs
        ls
        git config --global user.email ${{secrets.GH_EMAIL}}
        git config --global user.name ${{secrets.GH_USERNAME}}
        git remote set-url origin https://${{secrets.GH_ACCESS_TOKEN}}@github.com/${{secrets.GH_USERNAME}}/jsboardgamedemo.git
        git checkout --track origin/master
        git status
        git fetch
        git pull
    - name: Build and Pack
      run: npm run build
    - name: Deploy to GH Pages
      run: |
        git add .
        git commit -m "deploy pages"
        git status
        git push